version: '3'

services:

  api-mensagem:
    build: 
       context: .docker
    container_name: api-mensagem
    ports:
      - "8033:8080"
    volumes:
      - ./:/var/www/html
    networks:
      - kafka-network
    links:
      - kafka

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - 2181:2181

  kafka:
    image: wurstmeister/kafka
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks: 
  kafka-network:
    ipam:
      config:
        - subnet: 175.111.0.0/16